- name: Setup Docker and deploy containers
  hosts: oci-server
  become: true
  vars:
    wg_host: "{{ lookup('env', 'WG_HOST') }}"
    wg_password: "{{ lookup('env', 'WG_PASSWORD') }}"

  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        state: present
        update_cache: true

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      ansible.builtin.apt:
        name: docker-ce
        state: present
        update_cache: true

    - name: Add ubuntu user to docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: true

    - name: Generate compose file from template
      ansible.builtin.template:
        src: compose/vpn-server.yml.j2
        dest: /home/ubuntu/vpn-server.yml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Run docker-compose up
      become: false
      become_user: ubuntu
      ansible.builtin.command: sudo docker compose -f /home/ubuntu/vpn-server.yml up -d
      register: docker_compose_output
      changed_when: "'Creating' in docker_compose_output.stdout or 'Starting' in docker_compose_output.stdout"
